baseurl = "https://www.micheldebree.nl"
title = "Michel de Bree"

theme = "hugo-coder"
enableEmoji = true

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourdiscussshortname"

[params]
    author = "Michel de Bree"
    description = "Michel de Bree, Freelance Full Stack Java Developer"
    keywords = "developer,freelance,java,javascript,react,spring boot,hibernate,git,linux,docker,kubernetes"
    info = "Freelance Full Stack Java Developer"
    avatarurl = "images/logo.svg"
    footercontent = " "

    dateformat = "January 2, 2006"

    hideCredits = true
    hideCopyright = true

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = ["css/custom.css"]

    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Curriculum Vitae"
    icon = "fa fa-2x fa-address-card"
    weight = 1
    url = "/resume"
[[params.social]]
    name = "Email"
    icon = "fa fa-2x fa-envelope"
    weight = 1
    url = "mailto:michel@micheldebree.nl"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-2x fa-linkedin"
    weight = 1
    url = "https://www.linkedin.com/in/micheldebree/"
[[params.social]]
    name = "Github"
    icon = "fa fa-2x fa-github"
    weight = 2
    url = "https://github.com/micheldebree/"
[[params.social]]
    name = "Mastodon"
    icon = "fa fa-2x fa-mastodon"
    weight = 4
    url = "https://mastodon.nl/@micheldebree"
    rel = "me"
[[params.social]]
    name = "RSS"
    icon = "fa fa-2x fa-rss"
    weight = 5
    url = "https://www.micheldebree.nl/index.xml"

[params.googleTagManager]
id = "G-GRF7VLVEGM"

[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            #[[languages.en.menu.main]]
            #name = "About"
            #weight = 1
            #url = "about/"

            [[languages.en.menu.main]]
            name = "Resum√©"
            weight = 1
            url = "resume/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"


            # [[languages.en.menu.main]]
            # name = "Music"
            # weight = 3
            # url = "music/"

            # [[languages.en.menu.main]]
            # name = "Contact me"
            # weight = 5
            # url = "contact/"

